### ISSUE TITLE
Interactive avatar not working

### ISSUE THREAD

**Issue by grkhcl** [Azure/gen-cv#12]
Hi @harmke 

Hope you are doing good, Happy Thanksgiving 
We tried deploying interactive avatar,

But we are getting login page with username and password, if we remove the page we are just getting text and no avatar
web App code doesn't seem to work,

Can you please share latest web app code
also is the ICE connection string is communication service connection string ?

<img width="960" alt="MicrosoftTeams-image (11)" src="https://github.com/Azure/gen-cv/assets/112511579/cb1b9afe-8c21-46d6-a6db-3ccd80a38ebd">
<img width="955" alt="MicrosoftTeams-image (10)" src="https://github.com/Azure/gen-cv/assets/112511579/7eae7f78-96c1-4119-9036-c4f41cf6127d">

Thanks
Radhakrishnan Guhan

**Comment by harmke** [comment]
Hi @grkhcl 
The login page is just a dummy page, in case there's a need to integrate with a login system at a later stage. You can click on login without filling in any details.
The ICE connection string is indeed the Azure Communication Service connection string. The avatar will not load without filling it in, so that might be the issue here. You can follow this reference to create an instance: [Quickstart: Create and manage Communication Services resources](https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/create-communication-resource?tabs=windows&pivots=platform-azp#create-azure-communication-services-resource)
Let me know if this works for you.

**Comment by grkhcl** [comment]
Hi @harmke 

If we click on login page its just loading icon and nothing happens, if we remove the login page no avatar is showing 
Yes we have set up the ICE connection string as per the instructions only, can you please share your web app latest code 
we have a customer demo thought of showing this demo,
if its possible to set up call let me know, that would be great 

CHEERS
Radhakrishnan Guhan
radhakrishnan.guhan@hcl.com

**Comment by harmke** [comment]
Hi @grkhcl 
Do you see any error message in the browser console? This would help us identify the issue. Thanks in advance.

**Comment by grkhcl** [comment]
Hi @harmke 

We have following error
![MicrosoftTeams-image (12)](https://github.com/Azure/gen-cv/assets/112511579/2f270a64-a026-4447-9c98-db214f949086)

GetIceServerToken ,  getSpeechToken , unexpected end of JSON Input at main.js:58:32

**Comment by harmke** [comment]
Thank you for sharing! It seems that the front-end cannot reach the API. I just added the host.json to the API folder, could you check if it works now?

**Comment by grkhcl** [comment]
Hi @harmke 

Now I am getting different error 
![console error](https://github.com/Azure/gen-cv/assets/112511579/dfeffc1a-a9ec-4351-80d6-d89b71a0286f)

**Comment by harmke** [comment]
This seems to be the same error as you shared before.
Could you verify that you can run this project locally before deploying it in Azure? The error might be related to specific settings in your Azure tenant, and I won't be able to help with that.

**Comment by fbanespo1** [comment]
I am having also another problem with the azure-communication module I am not able to install it with pip

I am still having the same issue. I just click login and the wheel still running forever. Inspect the page I have found http://localhost:4280/api/getIceServerToken
Request Method:
POST
Status Code:
500 Internal Server Error
Remote Address:
127.0.0.1:4280
Referrer Policy:
same-origin
Access-Control-Allow-Origin:
*
Connection:
close
Content-Length:
0
Date:
Fri, 24 Nov 2023 20:23:35 GMT
Server:
Kestrel
Accept:
*/*
Accept-Encoding:
gzip, deflate, br
Accept-Language:
en-GB,en-US;q=0.9,en;q=0.8,it;q=0.7,es;q=0.6
Connection:
keep-alive
Content-Length:
0
Cookie:
ajs_anonymous_id=b35b6f29-3c5b-4d36-8d7b-9c8a046f8741; ajs_user_id=32077b58-baa4-5776-83ca-2fd1a403ebf9
Host:
localhost:4280
Origin:
http://localhost:4280
Referer:
http://localhost:4280/
Sec-Ch-Ua:
"Google Chrome";v="119", "Chromium";v="119", "Not?A_Brand";v="24"
Sec-Ch-Ua-Mobile:
?0
Sec-Ch-Ua-Platform:
"macOS"
Sec-Fetch-Dest:
empty
Sec-Fetch-Mode:
cors
Sec-Fetch-Site:
same-origin
User-Agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

**Comment by grkhcl** [comment]
Hi @harmke 
while running locally in windows system and windows vm we faced issue running the site 
instead of giving relative path for Get speechToken we gave endpoint url directly "https://westus2.api.cognitive.microsoft.com/sts/v1.0/issueToken;"

now we get avatar but it is not giving any response we get error message in fetch api/mesage

which environment you are running? mac/linux or windows ? did you have running version of this code in windows ?
![error 2](https://github.com/Azure/gen-cv/assets/112511579/476cb8e8-ffa1-419a-89eb-8832bb0126ed)

Thanks
Radhakrishnan

**Comment by thesaqibmumtaz** [comment]
Hi @grkhcl ,
Did you found the solution of this avatar appearance issue? 
If yes, can you please share the code or insights.

Thanks
