### ISSUE TITLE
crop the video generated from Text to Speech Avatar

### ISSUE THREAD

**Issue by shilpaCM** [Azure/gen-cv#16]
Hi,

Need to crop the video generated from Text to Speech Avatar part of our solution. Any references or which way we can crop the video either by using configuration or programmatically. using Speech SDK for JavaScript. 

thank you.

**Comment by harmke** [comment]
Hi @shilpaCM ,

The documentation for the avatar service can be found here: https://learn.microsoft.com/en-us/azure/ai-services/speech-service/text-to-speech-avatar/real-time-synthesis-avatar.
To change the size of the avatar, you can change the height and width properties in the html file, or add custom css to the styling sheet.

Regards,
Harmke
