### ISSUE TITLE
Resize Text to Speech Avatar video

### ISSUE THREAD

**Issue by shilpaCM** [Azure/gen-cv#17]
Hi,

How to resize & remove background color for the video generated from Text to Speech Avatar part of our solution. Any references using Speech SDK for JavaScript.

thank you.

**Comment by shilpaCM** [comment]
Hi, 
I am able to get Avatar with transparent background color, but audio is not coming. Any pointers or references will be useful.

**Comment by harmke** [comment]
Hi @shilpaCM,
Could you try to open the browser console, refresh the page and load the avatar again? Let me know if you see any error message coming up in the console. In most cases, this has to do with the configuration of the Azure resources or secrets.
Hope this helps!
