### ISSUE TITLE
SyntaxError: Unexpected end of JSON input at main.js:56:32

### ISSUE THREAD

**Issue by HappyGroupHub** [Azure/gen-cv#19]
I've already tested this soultion successfully locally, which everything works fine.
However, while deploying it to the Azure Static Web, after I clicked on the login button, the following error occurs and it won't jump to the main page.

![image](https://github.com/Azure/gen-cv/assets/43276256/bd7557ff-36eb-45ba-970c-fd44c122e3a7)

Again, it works great while running locally. This only happened after I deploy this apllication to Azure Static Web Apps.

**Comment by HappyGroupHub** [comment]
This is solved by uploading local.settings.json to the service

**Comment by luoanabecher** [comment]
Hello, I have the same issue, the local.settings.json values were added to the environment variables of the static app but i still have those issues.

**Comment by HappyGroupHub** [comment]
I think it might caused by incorrect environment variables, did you solve this problem already?
