### ISSUE TITLE
Facing Issue in avatar/interactive/src/js/main.js

### ISSUE THREAD

**Issue by cgytiam** [Azure/gen-cv#23]
While running the avatar app, from webpage inspect I am getting the below error which is from main.js,

_TypeError: SpeechSDK.AvatarVideoFormat is not a constructor_

which is getting generated from **connectToAvatarService** function and more specifically from the below line of the function,

`const videoFormat = new SpeechSDK.AvatarVideoFormat()`

Not able to understand, what is wrong here. Please help

**Comment by harmke** [comment]
Hi @cgytiam ,

I wasn't able to reproduce this issue. Could you give a bit more context on changes that you have made so far? Did you validate that the Speech SDK was successfully loaded in the index.html?

Regards,
Harmke
