### ISSUE TITLE
Interactive avatar api requirements.txt incomplete? 

### ISSUE THREAD

**Issue by corticalstack** [Azure/gen-cv#33]
Hi,

Following the setup guide for the interactive avatar camping demo, I weas getting a 404 when the front end was trying to execute the get-speech-token api route.

I belive this was because the managed Azure function was dumping out, as it did not have the necessary python package dependencies installed, for example openai. 

In the original repo, _requirements.txt has:

```
azure-functions
azurefunctions-extensions-http-fastapi
```

After adding:

```
azure-functions
openai
fastapi
aiohttp
pyodbc
requests
beautifulsoup4

```

The route can now be successfully consumed. Grateful for any confirmation there is an issue with the repo requirements.txt, or whether the environment is built correctly some other way (I'm very much a beginner when it comes to Azure static web apps).

Thanks

**Comment by harmke** [comment]
The requirements.txt has been updated in the meantime, let me know if you still have any issues with it.
