### ISSUE TITLE
Value AzureWebJobsStorage

### ISSUE THREAD

**Issue by fbanespo1** [Azure/gen-cv#9]
Hi Team,

I am trying to build the Avatar Interactive and I found a few issues on of them is AzureWebJobsStorage I don't understand from where I can get this value please?

Thanks
Tony

**Comment by harmke** [comment]
Hi @fbanespo1 
The AzureWebJobsStorage should not be required for running the demo, you can leave it empty. Thanks for pointing this out, I will clarify this in the readme. Please let me know which other issues you are encountering.
